import type { Subject, Chapter, QuizQuestion } from './types';

// Grade 9 Chapters
export const chapters: Chapter[] = [
  // Mathematics
  { id: 'g9-math-numsys', name: 'Number Systems', subjectId: 'math' },
  { id: 'g9-math-poly', name: 'Polynomials', subjectId: 'math' },
  { id: 'g9-math-coord', name: 'Coordinate Geometry', subjectId: 'math' },
  { id: 'g9-math-lineq', name: 'Linear Equations in Two Variables', subjectId: 'math' },
  { id: 'g9-math-euclid', name: 'Introduction to Euclid’s Geometry', subjectId: 'math' },
  { id: 'g9-math-linesangles', name: 'Lines and Angles', subjectId: 'math' },
  { id: 'g9-math-tri', name: 'Triangles', subjectId: 'math' },
  { id: 'g9-math-quad', name: 'Quadrilaterals', subjectId: 'math' },
  { id: 'g9-math-circles', name: 'Circles', subjectId: 'math' },
  { id: 'g9-math-heron', name: 'Heron’s Formula', subjectId: 'math' },
  { id: 'g9-math-surface', name: 'Surface Areas and Volumes', subjectId: 'math' },
  { id: 'g9-math-stats', name: 'Statistics', subjectId: 'math' },

  // Physics
  { id: 'g9-phy-motion', name: 'Motion', subjectId: 'phy' },
  { id: 'g9-phy-force', name: 'Force and Laws of Motion', subjectId: 'phy' },
  { id: 'g9-phy-grav', name: 'Gravitation', subjectId: 'phy' },
  { id: 'g9-phy-work', name: 'Work and Energy', subjectId: 'phy' },
  { id: 'g9-phy-sound', name: 'Sound', subjectId: 'phy' },

  // Chemistry
  { id: 'g9-chem-matter', name: 'Matter in Our Surroundings', subjectId: 'chem' },
  { id: 'g9-chem-pure', name: 'Is Matter Around Us Pure?', subjectId: 'chem' },
  { id: 'g9-chem-atoms', name: 'Atoms and Molecules', subjectId: 'chem' },
  { id: 'g9-chem-structure', name: 'Structure of the Atom', subjectId: 'chem' },

  // Biology
  { id: 'g9-bio-cell', name: 'The Fundamental Unit of Life (Cell)', subjectId: 'bio' },
  { id: 'g9-bio-tissues', name: 'Tissues', subjectId: 'bio' },
  { id: 'g9-bio-food', name: 'Improvement in Food Resources', subjectId: 'bio' },
];

const baseSubjects: Omit<Subject, 'chapters'>[] = [
  { id: 'math', name: 'Mathematics', iconName: 'Calculator' },
  { id: 'phy', name: 'Physics', iconName: 'Zap' },
  { id: 'chem', name: 'Chemistry', iconName: 'FlaskConical' },
  { id: 'bio', name: 'Biology', iconName: 'Leaf' },
];

export const subjects: Subject[] = baseSubjects.map((subject) => ({
  ...subject,
  chapters: chapters.filter((c) => c.subjectId === subject.id),
}));


export const quizQuestions: QuizQuestion[] = [
  // == Mathematics ==
  // Chapter: Number Systems (g9-math-numsys)
  {
    id: 101,
    chapterId: 'g9-math-numsys',
    question: 'Which of the following is an irrational number?',
    options: ['√4', '√9', '√2', '0.333...'],
    correctAnswer: 2,
    explanation: '√2 cannot be expressed as a simple fraction. √4=2 and √9=3 are integers. 0.333... is a rational number (1/3).',
  },
  {
    id: 102,
    chapterId: 'g9-math-numsys',
    question: 'The decimal expansion of a rational number is either terminating or...',
    options: ['Non-terminating non-repeating', 'Non-terminating repeating', 'Terminating repeating', 'None of the above'],
    correctAnswer: 1,
    explanation: 'Rational numbers have decimal expansions that either terminate or repeat in a pattern.',
  },
  {
    id: 117,
    chapterId: 'g9-math-numsys',
    question: 'What is the result of (3 + √3)(2 + √2)?',
    options: ['6 + 3√2 + 2√3 + √6', '6 + 5√5', '11 + √6', '5 + √6'],
    correctAnswer: 0,
    explanation: 'Use the distributive property (FOIL method): 3*2 + 3*√2 + √3*2 + √3*√2.',
  },
  {
    id: 118,
    chapterId: 'g9-math-numsys',
    question: 'Every rational number is a real number. True or False?',
    options: ['True', 'False'],
    correctAnswer: 0,
    explanation: 'The set of real numbers is composed of all rational and irrational numbers.',
  },
   {
    id: 119,
    chapterId: 'g9-math-numsys',
    question: 'Which of the following numbers has a terminating decimal expansion?',
    options: ['1/3', '1/7', '1/8', '1/6'],
    correctAnswer: 2,
    explanation: 'A rational number has a terminating decimal expansion if the prime factorization of the denominator contains only powers of 2 and/or 5. 8 = 2³.',
  },

  // Chapter: Polynomials (g9-math-poly)
  {
    id: 103,
    chapterId: 'g9-math-poly',
    question: 'What is the degree of the polynomial 5x³ + 4x² + 7x?',
    options: ['3', '2', '1', '4'],
    correctAnswer: 0,
    explanation: 'The degree of a polynomial is the highest exponent of its variable. Here, the highest exponent is 3.',
  },
  {
    id: 104,
    chapterId: 'g9-math-poly',
    question: 'If p(x) = x + 3, what is the value of p(x) + p(-x)?',
    options: ['6', '2x', '0', '3'],
    correctAnswer: 0,
    explanation: 'p(x) = x + 3 and p(-x) = -x + 3. So, (x + 3) + (-x + 3) = 6.',
  },
  {
    id: 120,
    chapterId: 'g9-math-poly',
    question: 'Which of the following is a zero of the polynomial x² - 5x + 6?',
    options: ['1', '4', '5', '2'],
    correctAnswer: 3,
    explanation: 'A zero is a value of x that makes the polynomial equal to 0. (2)² - 5(2) + 6 = 4 - 10 + 6 = 0.',
  },
  {
    id: 121,
    chapterId: 'g9-math-poly',
    question: 'What is the remainder when x³ + 1 is divided by x + 1?',
    options: ['0', '1', '2', '-1'],
    correctAnswer: 0,
    explanation: 'According to the Remainder Theorem, the remainder is f(-1). (-1)³ + 1 = -1 + 1 = 0.',
  },
  {
    id: 126,
    chapterId: 'g9-math-poly',
    question: 'The polynomial p(x) = 2x + 5 has a zero at:',
    options: ['5/2', '-5/2', '2/5', '-2/5'],
    correctAnswer: 1,
    explanation: 'To find the zero, set p(x) = 0. 2x + 5 = 0 => 2x = -5 => x = -5/2.',
  },

  // Chapter: Coordinate Geometry (g9-math-coord)
  {
    id: 105,
    chapterId: 'g9-math-coord',
    question: 'What are the coordinates of the origin in a Cartesian plane?',
    options: ['(1, 1)', '(0, 0)', '(1, 0)', '(0, 1)'],
    correctAnswer: 1,
    explanation: 'The origin is the point where the x-axis and y-axis intersect, which is at the coordinates (0, 0).',
  },
  {
    id: 106,
    chapterId: 'g9-math-coord',
    question: 'The point (-3, -5) lies in which quadrant?',
    options: ['First quadrant', 'Second quadrant', 'Third quadrant', 'Fourth quadrant'],
    correctAnswer: 2,
    explanation: 'In the third quadrant, both the x-coordinate and y-coordinate are negative.',
  },
  {
    id: 122,
    chapterId: 'g9-math-coord',
    question: 'What is the name of the horizontal line in the cartesian plane?',
    options: ['y-axis', 'origin', 'x-axis', 'quadrant'],
    correctAnswer: 2,
    explanation: 'The horizontal line is the x-axis, and the vertical line is the y-axis.',
  },
  {
    id: 127,
    chapterId: 'g9-math-coord',
    question: 'A point with a positive x-coordinate and a negative y-coordinate lies in which quadrant?',
    options: ['First quadrant', 'Second quadrant', 'Third quadrant', 'Fourth quadrant'],
    correctAnswer: 3,
    explanation: 'The fourth quadrant is defined by x > 0 and y < 0.',
  },
  {
    id: 128,
    chapterId: 'g9-math-coord',
    question: 'What is the abscissa of the point (4, -7)?',
    options: ['4', '-7', '0', '3'],
    correctAnswer: 0,
    explanation: 'The abscissa is another name for the x-coordinate of a point.',
  },

  // Chapter: Linear Equations in Two Variables (g9-math-lineq)
  {
    id: 107,
    chapterId: 'g9-math-lineq',
    question: 'How many solutions does the equation y = 3x + 5 have?',
    options: ['One solution', 'Two solutions', 'Infinitely many solutions', 'No solution'],
    correctAnswer: 2,
    explanation: 'For every value of x, you can find a corresponding value of y, resulting in an infinite number of (x, y) pairs.',
  },
  {
    id: 108,
    chapterId: 'g9-math-lineq',
    question: 'The graph of a linear equation in two variables is a...',
    options: ['Straight line', 'Circle', 'Parabola', 'Point'],
    correctAnswer: 0,
    explanation: 'The equation ax + by + c = 0 always represents a straight line on a graph.',
  },
  {
    id: 129,
    chapterId: 'g9-math-lineq',
    question: 'Which of the following points is a solution to the equation 2x + 3y = 12?',
    options: ['(3, 2)', '(2, 3)', '(4, 1)', '(0, 3)'],
    correctAnswer: 0,
    explanation: 'Substitute the coordinates into the equation: 2(3) + 3(2) = 6 + 6 = 12.',
  },
  {
    id: 130,
    chapterId: 'g9-math-lineq',
    question: 'The equation x = 7 in two variables can be written as:',
    options: ['x + y = 7', '1.x + 0.y = 7', '0.x + 1.y = 7', 'x - y = 7'],
    correctAnswer: 1,
    explanation: 'To express it in two variables, we can add a y term with a coefficient of 0, as it does not change the value of x.',
  },
  {
    id: 131,
    chapterId: 'g9-math-lineq',
    question: 'The graph of the equation y = a is a line parallel to the:',
    options: ['y-axis', 'x-axis', 'Both axes', 'Origin'],
    correctAnswer: 1,
    explanation: 'For any value of x, the y-coordinate is always \'a\', creating a horizontal line parallel to the x-axis.',
  },

  // Chapter: Introduction to Euclid’s Geometry (g9-math-euclid)
  {
    id: 109,
    chapterId: 'g9-math-euclid',
    question: 'According to Euclid\'s postulates, all right angles are equal to one another. True or False?',
    options: ['True', 'False'],
    correctAnswer: 0,
    explanation: 'This is Euclid\'s fourth postulate, a fundamental assumption in Euclidean geometry.',
  },
  {
    id: 123,
    chapterId: 'g9-math-euclid',
    question: '"Things which are equal to the same thing are equal to one another." This is one of Euclid\'s:',
    options: ['Postulates', 'Definitions', 'Axioms', 'Theorems'],
    correctAnswer: 2,
    explanation: 'This is Euclid\'s first axiom. Axioms are common notions used throughout mathematics, whereas postulates are specific to geometry.',
  },
  {
    id: 132,
    chapterId: 'g9-math-euclid',
    question: 'How many dimensions does a solid have?',
    options: ['One', 'Two', 'Three', 'Zero'],
    correctAnswer: 2,
    explanation: 'Solids have three dimensions: length, breadth, and height.',
  },
  {
    id: 133,
    chapterId: 'g9-math-euclid',
    question: 'A surface has length and breadth only. How many dimensions does it have?',
    options: ['One', 'Two', 'Three', 'Zero'],
    correctAnswer: 1,
    explanation: 'A surface is a two-dimensional figure with length and breadth.',
  },
  {
    id: 134,
    chapterId: 'g9-math-euclid',
    question: 'Euclid stated that "a terminated line can be produced indefinitely". This is a(n):',
    options: ['Axiom', 'Definition', 'Postulate', 'Theorem'],
    correctAnswer: 2,
    explanation: 'This is Euclid\'s second postulate, which deals with the properties of lines.',
  },

  // Chapter: Lines and Angles (g9-math-linesangles)
  {
    id: 110,
    chapterId: 'g9-math-linesangles',
    question: 'If two lines intersect, the vertically opposite angles are:',
    options: ['Complementary', 'Supplementary', 'Equal', 'Unequal'],
    correctAnswer: 2,
    explanation: 'When two lines intersect, the angles opposite each other at the vertex are always equal.',
  },
  {
    id: 124,
    chapterId: 'g9-math-linesangles',
    question: 'Two angles are complementary. If one angle is 40°, what is the other angle?',
    options: ['50°', '140°', '90°', '40°'],
    correctAnswer: 0,
    explanation: 'Complementary angles add up to 90°. So, 90° - 40° = 50°.',
  },
  {
    id: 135,
    chapterId: 'g9-math-linesangles',
    question: 'Two angles forming a linear pair are always:',
    options: ['Equal', 'Complementary', 'Supplementary', 'Vertically opposite'],
    correctAnswer: 2,
    explanation: 'A linear pair of angles are adjacent angles whose non-common sides are opposite rays. They always add up to 180° (supplementary).',
  },
  {
    id: 136,
    chapterId: 'g9-math-linesangles',
    question: 'If a transversal intersects two parallel lines, then each pair of corresponding angles is:',
    options: ['Equal', 'Complementary', 'Supplementary', 'Unequal'],
    correctAnswer: 0,
    explanation: 'This is a fundamental property of parallel lines and transversals.',
  },
  {
    id: 137,
    chapterId: 'g9-math-linesangles',
    question: 'An angle which is greater than 180° but less than 360° is called a(n):',
    options: ['Acute angle', 'Obtuse angle', 'Straight angle', 'Reflex angle'],
    correctAnswer: 3,
    explanation: 'A reflex angle is an angle that is more than 180 degrees and less than 360 degrees.',
  },

  // Chapter: Triangles (g9-math-tri)
  {
    id: 111,
    chapterId: 'g9-math-tri',
    question: 'What is the sum of angles in a triangle?',
    options: ['90 degrees', '180 degrees', '270 degrees', '360 degrees'],
    correctAnswer: 1,
    explanation: 'The sum of the interior angles of any triangle is always 180 degrees.',
  },
  {
    id: 125,
    chapterId: 'g9-math-tri',
    question: 'Which congruence rule applies if two sides and the included angle of one triangle are equal to two sides and the included angle of another triangle?',
    options: ['SSS', 'ASA', 'SAS', 'RHS'],
    correctAnswer: 2,
    explanation: 'This is the Side-Angle-Side (SAS) congruence criterion.',
  },
  {
    id: 138,
    chapterId: 'g9-math-tri',
    question: 'In an isosceles triangle, angles opposite to equal sides are:',
    options: ['Unequal', 'Right angles', 'Equal', 'Supplementary'],
    correctAnswer: 2,
    explanation: 'This is a property of isosceles triangles. The base angles are equal.',
  },
  {
    id: 139,
    chapterId: 'g9-math-tri',
    question: 'Which of the following cannot be the sides of a right-angled triangle?',
    options: ['3, 4, 5', '5, 12, 13', '8, 15, 17', '7, 8, 9'],
    correctAnswer: 3,
    explanation: 'A right-angled triangle must satisfy the Pythagorean theorem (a² + b² = c²). 7² + 8² = 49 + 64 = 113, which is not equal to 9² (81).',
  },
  {
    id: 140,
    chapterId: 'g9-math-tri',
    question: 'The sum of the lengths of any two sides of a triangle is always _____ the third side.',
    options: ['Less than', 'Equal to', 'Greater than', 'Half of'],
    correctAnswer: 2,
    explanation: 'This is the Triangle Inequality Theorem, a fundamental property of all triangles.',
  },

  // Chapter: Quadrilaterals (g9-math-quad)
  {
    id: 112,
    chapterId: 'g9-math-quad',
    question: 'A quadrilateral with all four sides equal and all four angles right angles is a:',
    options: ['Rhombus', 'Rectangle', 'Square', 'Trapezium'],
    correctAnswer: 2,
    explanation: 'A square has four equal sides and four 90-degree angles.',
  },
  {
    id: 141,
    chapterId: 'g9-math-quad',
    question: 'The sum of all angles in a quadrilateral is:',
    options: ['180°', '270°', '360°', '540°'],
    correctAnswer: 2,
    explanation: 'A quadrilateral can be divided into two triangles, so the sum of its angles is 2 * 180° = 360°.',
  },
  {
    id: 142,
    chapterId: 'g9-math-quad',
    question: 'A quadrilateral with one pair of opposite sides parallel is called a:',
    options: ['Parallelogram', 'Rhombus', 'Trapezium', 'Kite'],
    correctAnswer: 2,
    explanation: 'This is the definition of a trapezium (or trapezoid).',
  },
  {
    id: 143,
    chapterId: 'g9-math-quad',
    question: 'The diagonals of a parallelogram:',
    options: ['Are equal', 'Are perpendicular', 'Bisect each other', 'Bisect the angles'],
    correctAnswer: 2,
    explanation: 'A key property of a parallelogram is that its diagonals cut each other into two equal halves.',
  },
  {
    id: 144,
    chapterId: 'g9-math-quad',
    question: 'A rhombus is a quadrilateral with:',
    options: ['All sides equal', 'All angles equal', 'One pair of parallel sides', 'Diagonals are equal'],
    correctAnswer: 0,
    explanation: 'The defining property of a rhombus is that all four of its sides have the same length.',
  },

  // Chapter: Circles (g9-math-circles)
  {
    id: 113,
    chapterId: 'g9-math-circles',
    question: 'The longest chord in a circle is called the:',
    options: ['Radius', 'Tangent', 'Secant', 'Diameter'],
    correctAnswer: 3,
    explanation: 'The diameter is a chord that passes through the center of the circle, making it the longest possible chord.',
  },
  {
    id: 145,
    chapterId: 'g9-math-circles',
    question: 'The angle subtended by an arc at the center is ______ the angle subtended by it at any point on the remaining part of the circle.',
    options: ['Half', 'Equal to', 'Double', 'Triple'],
    correctAnswer: 2,
    explanation: 'This is a fundamental theorem of circles relating the central angle and the inscribed angle.',
  },
  {
    id: 146,
    chapterId: 'g9-math-circles',
    question: 'How many tangents can be drawn to a circle from a point outside the circle?',
    options: ['One', 'Two', 'Infinite', 'Zero'],
    correctAnswer: 1,
    explanation: 'Exactly two tangents can be drawn from an external point to a circle.',
  },
  {
    id: 147,
    chapterId: 'g9-math-circles',
    question: 'A line intersecting a circle in two points is called a:',
    options: ['Tangent', 'Secant', 'Chord', 'Radius'],
    correctAnswer: 1,
    explanation: 'A secant is a line that intersects a circle at two distinct points.',
  },
  {
    id: 148,
    chapterId: 'g9-math-circles',
    question: 'Angles in the same segment of a circle are:',
    options: ['Equal', 'Complementary', 'Supplementary', 'Unequal'],
    correctAnswer: 0,
    explanation: 'This theorem states that any angles subtended by the same arc at the circumference are equal.',
  },
  
  // Chapter: Heron’s Formula (g9-math-heron)
  {
    id: 114,
    chapterId: 'g9-math-heron',
    question: 'Heron\'s formula is used to calculate the area of a:',
    options: ['Circle', 'Square', 'Triangle', 'Rectangle'],
    correctAnswer: 2,
    explanation: 'Heron\'s formula calculates the area of a triangle when the lengths of all three sides are known.',
  },
  {
    id: 149,
    chapterId: 'g9-math-heron',
    question: 'In Heron\'s formula, what does \'s\' represent?',
    options: ['Side length', 'Sum of sides', 'Semi-perimeter', 'Square root'],
    correctAnswer: 2,
    explanation: 's = (a + b + c) / 2, where a, b, and c are the side lengths of the triangle.',
  },
  {
    id: 150,
    chapterId: 'g9-math-heron',
    question: 'What is the area of an equilateral triangle with side length \'a\'?',
    options: ['a²/2', '(√3/4)a²', '(√3/2)a²', 'a²'],
    correctAnswer: 1,
    explanation: 'Using Heron\'s formula or standard trigonometry, the area of an equilateral triangle is (√3/4)a².',
  },
  {
    id: 151,
    chapterId: 'g9-math-heron',
    question: 'A triangle has sides 13 cm, 14 cm, and 15 cm. What is its semi-perimeter?',
    options: ['42 cm', '21 cm', '28 cm', '14 cm'],
    correctAnswer: 1,
    explanation: 's = (13 + 14 + 15) / 2 = 42 / 2 = 21 cm.',
  },
  {
    id: 152,
    chapterId: 'g9-math-heron',
    question: 'The sides of a triangular plot are in the ratio 3:5:7 and its perimeter is 300 m. Find its area.',
    options: ['1500√3 m²', '1000√3 m²', '500√3 m²', '3000√3 m²'],
    correctAnswer: 0,
    explanation: 'Sides are 60, 100, 140. s=150. Area = √[150(90)(50)(10)] = 1500√3.',
  },

  // Chapter: Surface Areas and Volumes (g9-math-surface)
  {
    id: 115,
    chapterId: 'g9-math-surface',
    question: 'What is the formula for the volume of a sphere?',
    options: ['πr²h', '2πrh', '4πr²', '(4/3)πr³'],
    correctAnswer: 3,
    explanation: 'The volume of a sphere with radius r is given by the formula V = (4/3)πr³.',
  },
  {
    id: 153,
    chapterId: 'g9-math-surface',
    question: 'What is the total surface area of a cube with side length \'a\'?',
    options: ['a³', '4a²', '6a²', 'a²'],
    correctAnswer: 2,
    explanation: 'A cube has 6 faces, and each face is a square with area a². So the total surface area is 6a².',
  },
  {
    id: 154,
    chapterId: 'g9-math-surface',
    question: 'The formula for the curved surface area of a cylinder is:',
    options: ['2πr(r+h)', 'πr²h', '2πr²', '2πrh'],
    correctAnswer: 3,
    explanation: 'The curved surface area of a cylinder with radius r and height h is 2πrh.',
  },
  {
    id: 155,
    chapterId: 'g9-math-surface',
    question: 'If the radius of a sphere is doubled, its volume becomes:',
    options: ['2 times', '4 times', '6 times', '8 times'],
    correctAnswer: 3,
    explanation: 'Volume is proportional to r³. If r becomes 2r, the volume becomes (2r)³ = 8r³, which is 8 times the original.',
  },
  {
    id: 156,
    chapterId: 'g9-math-surface',
    question: 'What is the volume of a cone with radius \'r\' and height \'h\'?',
    options: ['πr²h', '(1/3)πr²h', 'πrl', '2πrh'],
    correctAnswer: 1,
    explanation: 'The volume of a cone is one-third the volume of a cylinder with the same base radius and height.',
  },

  // Chapter: Statistics (g9-math-stats)
  {
    id: 116,
    chapterId: 'g9-math-stats',
    question: 'What is the mode of the following data set: 2, 3, 5, 3, 7, 3, 8?',
    options: ['5', '3', '7', '8'],
    correctAnswer: 1,
    explanation: 'The mode is the number that appears most frequently in a data set. In this case, 3 appears three times.',
  },
  {
    id: 157,
    chapterId: 'g9-math-stats',
    question: 'What is the median of the data: 2, 5, 8, 4, 9, 6, 1?',
    options: ['4', '9', '5', '6'],
    correctAnswer: 2,
    explanation: 'First, arrange the data in order: 1, 2, 4, 5, 6, 8, 9. The median is the middle value, which is 5.',
  },
  {
    id: 158,
    chapterId: 'g9-math-stats',
    question: 'The range of the data 25, 18, 20, 22, 16, 6, 17, 15, 12, 30, 32 is:',
    options: ['10', '15', '18', '26'],
    correctAnswer: 3,
    explanation: 'Range = Highest value - Lowest value = 32 - 6 = 26.',
  },
  {
    id: 159,
    chapterId: 'g9-math-stats',
    question: 'What is the mean of the first five natural numbers?',
    options: ['2', '3', '4', '5'],
    correctAnswer: 1,
    explanation: 'The first five natural numbers are 1, 2, 3, 4, 5. Mean = (1+2+3+4+5)/5 = 15/5 = 3.',
  },
  {
    id: 160,
    chapterId: 'g9-math-stats',
    question: 'A graphical representation of a frequency distribution is called a:',
    options: ['Bar graph', 'Pictograph', 'Pie chart', 'Histogram'],
    correctAnswer: 3,
    explanation: 'A histogram is a bar graph-like representation of data that buckets a range of outcomes into columns along the x-axis.',
  },

  // == Physics ==
  // Chapter: Motion (g9-phy-motion)
  {
    id: 201,
    chapterId: 'g9-phy-motion',
    question: 'Which of the following is a vector quantity?',
    options: ['Speed', 'Distance', 'Mass', 'Velocity'],
    correctAnswer: 3,
    explanation: 'Velocity has both magnitude and direction, making it a vector quantity. Speed, distance, and mass are scalar quantities.',
  },
  {
    id: 202,
    chapterId: 'g9-phy-motion',
    question: 'Acceleration is the rate of change of:',
    options: ['Distance', 'Speed', 'Velocity', 'Time'],
    correctAnswer: 2,
    explanation: 'Acceleration is defined as the rate at which an object changes its velocity.',
  },
   {
    id: 208,
    chapterId: 'g9-phy-motion',
    question: 'A car accelerates uniformly from 18 km/h to 36 km/h in 5 seconds. What is its acceleration?',
    options: ['1 m/s²', '2 m/s²', '3.6 m/s²', '5 m/s²'],
    correctAnswer: 0,
    explanation: 'First, convert speeds to m/s: 18 km/h = 5 m/s, 36 km/h = 10 m/s. Then use a = (v-u)/t. a = (10-5)/5 = 1 m/s².',
  },
  {
    id: 209,
    chapterId: 'g9-phy-motion',
    question: 'The area under a velocity-time graph represents:',
    options: ['Speed', 'Acceleration', 'Displacement', 'Force'],
    correctAnswer: 2,
    explanation: 'The area under a v-t graph gives the displacement of the object.',
  },
  {
    id: 214,
    chapterId: 'g9-phy-motion',
    question: 'Which equation of motion relates initial velocity (u), final velocity (v), acceleration (a) and displacement (s)?',
    options: ['v = u + at', 's = ut + ½at²', 'v² = u² + 2as', 's = (u+v)t / 2'],
    correctAnswer: 2,
    explanation: 'v² = u² + 2as is the third equation of motion, which does not involve time (t).',
  },

  // Chapter: Force and Laws of Motion (g9-phy-force)
  {
    id: 203,
    chapterId: 'g9-phy-force',
    question: 'What is Newton\'s second law of motion?',
    options: ['F=ma', 'E=mc²', 'v=u+at', 'P=V*I'],
    correctAnswer: 0,
    explanation: 'Newton\'s second law states that the force on an object is equal to its mass times its acceleration (F=ma).',
  },
  {
    id: 204,
    chapterId: 'g9-phy-force',
    question: 'Inertia is the property of a body to resist a change in its state of:',
    options: ['Rest only', 'Motion only', 'Rest or uniform motion', 'Acceleration'],
    correctAnswer: 2,
    explanation: 'Inertia is the resistance of any physical object to any change in its velocity.',
  },
  {
    id: 210,
    chapterId: 'g9-phy-force',
    question: 'Momentum is the product of mass and __________.',
    options: ['Acceleration', 'Velocity', 'Force', 'Distance'],
    correctAnswer: 1,
    explanation: 'Momentum (p) is defined as mass (m) times velocity (v), p = mv.',
  },
  {
    id: 215,
    chapterId: 'g9-phy-force',
    question: 'When a gun is fired, it recoils. This is an example of:',
    options: ['Newton\'s First Law', 'Newton\'s Second Law', 'Newton\'s Third Law', 'Law of Conservation of Energy'],
    correctAnswer: 2,
    explanation: 'The force on the bullet is equal and opposite to the force on the gun (recoil), which is an application of Newton\'s Third Law.',
  },
  {
    id: 216,
    chapterId: 'g9-phy-force',
    question: 'The SI unit of force is:',
    options: ['Joule', 'Watt', 'Newton', 'Pascal'],
    correctAnswer: 2,
    explanation: 'The SI unit of force is the Newton (N), which is defined as kg⋅m/s².',
  },

  // Chapter: Gravitation (g9-phy-grav)
  {
    id: 205,
    chapterId: 'g9-phy-grav',
    question: 'The value of acceleration due to gravity (g) is highest at:',
    options: ['The equator', 'The poles', 'The center of the Earth', 'It is constant everywhere'],
    correctAnswer: 1,
    explanation: 'The Earth is not a perfect sphere; it is slightly flattened at the poles. Since g is inversely proportional to the square of the distance from the center, it is highest at the poles.',
  },
  {
    id: 211,
    chapterId: 'g9-phy-grav',
    question: 'The weight of an object on the moon is about ____ of its weight on Earth.',
    options: ['1/2', '1/4', '1/6', 'The same as'],
    correctAnswer: 2,
    explanation: 'The moon\'s gravity is much weaker than Earth\'s, approximately one-sixth.',
  },
  {
    id: 217,
    chapterId: 'g9-phy-grav',
    question: 'The force of attraction between two unit masses separated by a unit distance is called:',
    options: ['Gravitational potential', 'Acceleration due to gravity', 'Universal gravitational constant', 'Gravitational field'],
    correctAnswer: 2,
    explanation: 'This is the definition of the Universal Gravitational Constant, G.',
  },
  {
    id: 218,
    chapterId: 'g9-phy-grav',
    question: 'An object is thrown vertically upwards. At its highest point, its acceleration is:',
    options: ['Zero', 'Upwards', 'Downwards (g)', 'Variable'],
    correctAnswer: 2,
    explanation: 'Even at the highest point when velocity is momentarily zero, the acceleration due to gravity (g) is still acting on it, pulling it downwards.',
  },
  {
    id: 219,
    chapterId: 'g9-phy-grav',
    question: 'Mass is a measure of an object\'s inertia, while weight is a measure of:',
    options: ['Volume', 'Density', 'The force of gravity on it', 'Its size'],
    correctAnswer: 2,
    explanation: 'Weight is a force, specifically the force of gravity acting on an object\'s mass (W = mg).',
  },

  // Chapter: Work and Energy (g9-phy-work)
  {
    id: 206,
    chapterId: 'g9-phy-work',
    question: 'The unit of work is:',
    options: ['Watt', 'Newton', 'Joule', 'Pascal'],
    correctAnswer: 2,
    explanation: 'The SI unit of work and energy is the Joule (J).',
  },
  {
    id: 212,
    chapterId: 'g9-phy-work',
    question: 'An object of mass 10 kg is moving with a velocity of 5 m/s. What is its kinetic energy?',
    options: ['25 J', '50 J', '125 J', '250 J'],
    correctAnswer: 2,
    explanation: 'Kinetic Energy (KE) = 1/2 * m * v². KE = 0.5 * 10 * (5)² = 0.5 * 10 * 25 = 125 J.',
  },
  {
    id: 220,
    chapterId: 'g9-phy-work',
    question: 'The energy possessed by an object due to its position or configuration is called:',
    options: ['Kinetic Energy', 'Potential Energy', 'Chemical Energy', 'Heat Energy'],
    correctAnswer: 1,
    explanation: 'This is the definition of potential energy. For example, gravitational potential energy depends on height.',
  },
  {
    id: 221,
    chapterId: 'g9-phy-work',
    question: 'What is the commercial unit of energy?',
    options: ['Joule', 'Watt-hour', 'Kilowatt-hour (kWh)', 'Calorie'],
    correctAnswer: 2,
    explanation: 'Kilowatt-hour (kWh) is commonly used by utility companies to measure energy consumption. 1 kWh = 3.6 x 10⁶ J.',
  },
  {
    id: 222,
    chapterId: 'g9-phy-work',
    question: 'The law of conservation of energy states that energy can neither be created nor destroyed, but can be:',
    options: ['Lost', 'Gained', 'Changed from one form to another', 'Measured'],
    correctAnswer: 2,
    explanation: 'This fundamental law states that the total energy of an isolated system remains constant.',
  },

  // Chapter: Sound (g9-phy-sound)
  {
    id: 207,
    chapterId: 'g9-phy-sound',
    question: 'Sound waves cannot travel through:',
    options: ['Solid', 'Liquid', 'Gas', 'Vacuum'],
    correctAnswer: 3,
    explanation: 'Sound is a mechanical wave, which means it requires a medium (particles) to propagate. A vacuum is empty of matter.',
  },
  {
    id: 213,
    chapterId: 'g9-phy-sound',
    question: 'The persistence of sound due to repeated reflection is called:',
    options: ['Echo', 'Reverberation', 'Pitch', 'Loudness'],
    correctAnswer: 1,
    explanation: 'Reverberation is the collection of reflected sounds from the surfaces in an enclosure.',
  },
  {
    id: 223,
    chapterId: 'g9-phy-sound',
    question: 'The audible range of frequency for human beings is approximately:',
    options: ['20 Hz to 20,000 Hz', 'Below 20 Hz', 'Above 20,000 Hz', '0 Hz to 100 Hz'],
    correctAnswer: 0,
    explanation: 'Humans can typically hear sound frequencies between 20 Hz and 20 kHz.',
  },
  {
    id: 224,
    chapterId: 'g9-phy-sound',
    question: 'The loudness of a sound is determined by its:',
    options: ['Frequency', 'Wavelength', 'Amplitude', 'Speed'],
    correctAnswer: 2,
    explanation: 'The amplitude of a sound wave determines its loudness or intensity.',
  },
  {
    id: 225,
    chapterId: 'g9-phy-sound',
    question: 'The pitch of a sound is determined by its:',
    options: ['Frequency', 'Wavelength', 'Amplitude', 'Speed'],
    correctAnswer: 0,
    explanation: 'The frequency of a sound wave determines its pitch (how high or low it sounds).',
  },
  
  // == Chemistry ==
  // Chapter: Matter in Our Surroundings (g9-chem-matter)
  {
    id: 301,
    chapterId: 'g9-chem-matter',
    question: 'The process of a solid turning directly into a gas is called:',
    options: ['Evaporation', 'Condensation', 'Sublimation', 'Melting'],
    correctAnswer: 2,
    explanation: 'Sublimation is the phase transition of a substance directly from the solid to the gas state, without passing through the liquid state.',
  },
  {
    id: 302,
    chapterId: 'g9-chem-matter',
    question: 'Which state of matter has a definite volume but no definite shape?',
    options: ['Solid', 'Liquid', 'Gas', 'Plasma'],
    correctAnswer: 1,
    explanation: 'Liquids take the shape of their container but have a fixed volume.',
  },
  {
    id: 307,
    chapterId: 'g9-chem-matter',
    question: 'What is the boiling point of water in Kelvin?',
    options: ['273 K', '373 K', '100 K', '0 K'],
    correctAnswer: 1,
    explanation: 'The boiling point of water is 100°C. To convert Celsius to Kelvin, you add 273.15. So, 100 + 273.15 = 373.15 K.',
  },
  {
    id: 308,
    chapterId: 'g9-chem-matter',
    question: 'Evaporation causes:',
    options: ['Heating', 'Cooling', 'No change in temperature', 'An increase in pressure'],
    correctAnswer: 1,
    explanation: 'The particles of a liquid absorb energy from the surroundings to evaporate, which leads to a cooling effect.',
  },
  {
    id: 312,
    chapterId: 'g9-chem-matter',
    question: 'Which state of matter has particles with the highest kinetic energy?',
    options: ['Solid', 'Liquid', 'Gas', 'All are equal'],
    correctAnswer: 2,
    explanation: 'Gas particles move rapidly and randomly, possessing the highest kinetic energy among the three common states.',
  },
  
  // Chapter: Is Matter Around Us Pure? (g9-chem-pure)
  {
    id: 303,
    chapterId: 'g9-chem-pure',
    question: 'Which of the following is a mixture?',
    options: ['Salt', 'Water', 'Air', 'Sugar'],
    correctAnswer: 2,
    explanation: 'Air is a mixture of various gases like nitrogen, oxygen, argon, and carbon dioxide.',
  },
  {
    id: 304,
    chapterId: 'g9-chem-pure',
    question: 'A solution in which no more solute can be dissolved at a given temperature is known as:',
    options: ['Unsaturated solution', 'Saturated solution', 'Supersaturated solution', 'Colloid'],
    correctAnswer: 1,
    explanation: 'A saturated solution contains the maximum amount of solute that will dissolve in a solvent at that temperature.',
  },
  {
    id: 309,
    chapterId: 'g9-chem-pure',
    question: 'Which of these is a chemical change?',
    options: ['Melting of ice', 'Dissolving salt in water', 'Burning of wood', 'Boiling of water'],
    correctAnswer: 2,
    explanation: 'Burning wood (combustion) is a chemical change because it results in new substances (ash, smoke, CO2).',
  },
  {
    id: 313,
    chapterId: 'g9-chem-pure',
    question: 'Milk is an example of a:',
    options: ['Solution', 'Suspension', 'Colloid', 'Pure substance'],
    correctAnswer: 2,
    explanation: 'Milk is a colloid, specifically an emulsion, where fat globules are dispersed in a water-based liquid.',
  },
  {
    id: 314,
    chapterId: 'g9-chem-pure',
    question: 'The components of a mixture can be separated by:',
    options: ['Chemical methods only', 'Physical methods only', 'Both physical and chemical methods', 'Neither method'],
    correctAnswer: 1,
    explanation: 'Mixtures can be separated by physical means such as filtration, evaporation, distillation, etc., because no chemical bonds are formed between the components.',
  },

  // Chapter: Atoms and Molecules (g9-chem-atoms)
  {
    id: 305,
    chapterId: 'g9-chem-atoms',
    question: 'What is the chemical formula for water?',
    options: ['CO₂', 'O₂', 'H₂O₂', 'H₂O'],
    correctAnswer: 3,
    explanation: 'A molecule of water is composed of two hydrogen atoms and one oxygen atom.',
  },
  {
    id: 310,
    chapterId: 'g9-chem-atoms',
    question: 'What is Avogadro\'s number?',
    options: ['6.022 x 10²³', '3.14 x 10¹⁵', '9.8 x 10⁸', '1.602 x 10⁻¹⁹'],
    correctAnswer: 0,
    explanation: 'Avogadro\'s number is the number of constituent particles (usually atoms or molecules) that are contained in one mole of a substance.',
  },
  {
    id: 315,
    chapterId: 'g9-chem-atoms',
    question: 'What is the molar mass of CO₂? (Atomic mass C=12, O=16)',
    options: ['28 g/mol', '32 g/mol', '44 g/mol', '56 g/mol'],
    correctAnswer: 2,
    explanation: 'Molar mass of CO₂ = 1 * (mass of C) + 2 * (mass of O) = 12 + 2 * 16 = 12 + 32 = 44 g/mol.',
  },
  {
    id: 316,
    chapterId: 'g9-chem-atoms',
    question: 'The law of conservation of mass states that mass is neither created nor _____ in a chemical reaction.',
    options: ['Destroyed', 'Changed', 'Multiplied', 'Reduced'],
    correctAnswer: 0,
    explanation: 'This fundamental law means the mass of the reactants must equal the mass of the products.',
  },
  {
    id: 317,
    chapterId: 'g9-chem-atoms',
    question: 'A group of atoms carrying a charge is known as a(n):',
    options: ['Molecule', 'Element', 'Polyatomic ion', 'Isotope'],
    correctAnswer: 2,
    explanation: 'For example, the sulfate ion (SO₄²⁻) is a polyatomic ion.',
  },
  
  // Chapter: Structure of the Atom (g9-chem-structure)
  {
    id: 306,
    chapterId: 'g9-chem-structure',
    question: 'Which subatomic particle has a negative charge?',
    options: ['Proton', 'Neutron', 'Electron', 'Photon'],
    correctAnswer: 2,
    explanation: 'Electrons are negatively charged particles that orbit the nucleus of an atom.',
  },
  {
    id: 311,
    chapterId: 'g9-chem-structure',
    question: 'Isotopes are atoms of the same element with a different number of:',
    options: ['Protons', 'Electrons', 'Neutrons', 'Ions'],
    correctAnswer: 2,
    explanation: 'Isotopes have the same number of protons (same atomic number) but different numbers of neutrons (different mass number).',
  },
  {
    id: 318,
    chapterId: 'g9-chem-structure',
    question: 'The nucleus of an atom contains:',
    options: ['Protons only', 'Electrons only', 'Protons and neutrons', 'Neutrons and electrons'],
    correctAnswer: 2,
    explanation: 'The dense central nucleus contains protons and neutrons, collectively known as nucleons.',
  },
  {
    id: 319,
    chapterId: 'g9-chem-structure',
    question: 'The atomic number of an element is the number of ______ in its nucleus.',
    options: ['Neutrons', 'Electrons', 'Protons', 'Nucleons'],
    correctAnswer: 2,
    explanation: 'The atomic number (Z) uniquely identifies a chemical element and is equal to the number of protons.',
  },
  {
    id: 320,
    chapterId: 'g9-chem-structure',
    question: 'Who discovered the electron?',
    options: ['Rutherford', 'Chadwick', 'J.J. Thomson', 'Goldstein'],
    correctAnswer: 2,
    explanation: 'J.J. Thomson is credited with the discovery of the electron in 1897 through his experiments with cathode ray tubes.',
  },

  // == Biology ==
  // Chapter: The Fundamental Unit of Life (Cell) (g9-bio-cell)
  {
    id: 401,
    chapterId: 'g9-bio-cell',
    question: 'What is the powerhouse of the cell?',
    options: ['Nucleus', 'Ribosome', 'Mitochondrion', 'Chloroplast'],
    correctAnswer: 2,
    explanation: 'Mitochondria are responsible for generating most of the cell\'s supply of adenosine triphosphate (ATP).',
  },
  {
    id: 402,
    chapterId: 'g9-bio-cell',
    question: 'Which organelle is known as the "suicide bag" of the cell?',
    options: ['Lysosome', 'Ribosome', 'Vacuole', 'Golgi apparatus'],
    correctAnswer: 0,
    explanation: 'Lysosomes contain digestive enzymes. If the cell is damaged, they can burst and digest the entire cell.',
  },
  {
    id: 406,
    chapterId: 'g9-bio-cell',
    question: 'Which of the following is found in plant cells but not in animal cells?',
    options: ['Cell membrane', 'Nucleus', 'Mitochondria', 'Cell wall'],
    correctAnswer: 3,
    explanation: 'Plant cells have a rigid cell wall outside the cell membrane for structural support. Animal cells do not.',
  },
   {
    id: 407,
    chapterId: 'g9-bio-cell',
    question: 'Where is DNA located in a eukaryotic cell?',
    options: ['Cytoplasm', 'Ribosome', 'Nucleus', 'Vacuole'],
    correctAnswer: 2,
    explanation: 'In eukaryotic cells, the vast majority of the genetic material (DNA) is contained within the nucleus.',
  },
  {
    id: 410,
    chapterId: 'g9-bio-cell',
    question: 'Which organelle is responsible for protein synthesis?',
    options: ['Golgi apparatus', 'Ribosome', 'Lysosome', 'Mitochondrion'],
    correctAnswer: 1,
    explanation: 'Ribosomes are the cellular machinery responsible for making proteins.',
  },

  // Chapter: Tissues (g9-bio-tissues)
  {
    id: 403,
    chapterId: 'g9-bio-tissues',
    question: 'Which type of tissue is responsible for movement in our body?',
    options: ['Epithelial tissue', 'Connective tissue', 'Muscular tissue', 'Nervous tissue'],
    correctAnswer: 2,
    explanation: 'Muscular tissue is composed of cells that have the special ability to shorten or contract in order to produce movement.',
  },
  {
    id: 404,
    chapterId: 'g9-bio-tissues',
    question: 'Blood is an example of which type of tissue?',
    options: ['Epithelial tissue', 'Connective tissue', 'Muscular tissue', 'Nervous tissue'],
    correctAnswer: 1,
    explanation: 'Blood is considered a specialized form of connective tissue because it has a matrix (plasma).',
  },
  {
    id: 408,
    chapterId: 'g9-bio-tissues',
    question: 'Which plant tissue is responsible for transporting water and minerals from the roots to the rest of the plant?',
    options: ['Phloem', 'Xylem', 'Parenchyma', 'Sclerenchyma'],
    correctAnswer: 1,
    explanation: 'Xylem is the vascular tissue in plants that conducts water and dissolved nutrients upward from the root.',
  },
  {
    id: 411,
    chapterId: 'g9-bio-tissues',
    question: 'Which tissue type forms the brain, spinal cord, and nerves?',
    options: ['Connective tissue', 'Epithelial tissue', 'Muscular tissue', 'Nervous tissue'],
    correctAnswer: 3,
    explanation: 'Nervous tissue is the main component of the nervous system, which controls the body\'s functions.',
  },
  {
    id: 412,
    chapterId: 'g9-bio-tissues',
    question: 'Which plant tissue transports food (sugars) from the leaves to other parts of the plant?',
    options: ['Xylem', 'Phloem', 'Meristem', 'Epidermis'],
    correctAnswer: 1,
    explanation: 'Phloem is the vascular tissue responsible for transporting sugars, produced during photosynthesis, to parts of the plant where they are needed for growth or storage.',
  },

  // Chapter: Improvement in Food Resources (g9-bio-food)
  {
    id: 405,
    chapterId: 'g9-bio-food',
    question: 'Which of the following is a Kharif crop?',
    options: ['Wheat', 'Pea', 'Paddy (Rice)', 'Mustard'],
    correctAnswer: 2,
    explanation: 'Kharif crops are grown with the onset of monsoon. Examples include paddy, maize, and cotton.',
  },
  {
    id: 409,
    chapterId: 'g9-bio-food',
    question: 'The practice of growing two or more crops in a definite row pattern is known as:',
    options: ['Crop rotation', 'Mixed cropping', 'Intercropping', 'Fallowing'],
    correctAnswer: 2,
    explanation: 'Intercropping involves growing two or more crops simultaneously in the same field in a definite pattern.',
  },
  {
    id: 413,
    chapterId: 'g9-bio-food',
    question: 'Which of the following is a Rabi crop?',
    options: ['Maize', 'Soyabean', 'Cotton', 'Wheat'],
    correctAnswer: 3,
    explanation: 'Rabi crops are sown in winter and harvested in spring. Wheat is a primary example.',
  },
  {
    id: 414,
    chapterId: 'g9-bio-food',
    question: 'The process of supplying water to crops at different intervals is called:',
    options: ['Weeding', 'Sowing', 'Irrigation', 'Harvesting'],
    correctAnswer: 2,
    explanation: 'Irrigation is the artificial application of water to the land or soil to assist in growing crops.',
  },
  {
    id: 415,
    chapterId: 'g9-bio-food',
    question: 'Apiculture is the scientific method of rearing:',
    options: ['Fish', 'Silkworms', 'Honey Bees', 'Birds'],
    correctAnswer: 2,
    explanation: 'Apiculture, or beekeeping, is the maintenance of bee colonies, commonly in man-made hives.',
  },
];
