import type { RevisionItem } from './types';

export const revisionContent: RevisionItem[] = [
  // Grade 9 - Math - Algebra (7 items)
  {
    id: 'math-9-1',
    subjectId: 'math',
    chapterId: 'alg',
    grade: '9',
    type: 'formula',
    topic: 'Square of a Binomial (Sum)',
    content: '(a + b)² = a² + 2ab + b²',
    question: 'What is the expansion of (x + 3)²?',
    options: ['x² + 9', 'x² + 6x + 9', 'x² + 3x + 9', 'x + 6'],
    correctAnswer: 1,
  },
  {
    id: 'math-9-2',
    subjectId: 'math',
    chapterId: 'alg',
    grade: '9',
    type: 'formula',
    topic: 'Square of a Binomial (Difference)',
    content: '(a - b)² = a² - 2ab + b²',
    question: 'What is the expansion of (y - 5)²?',
    options: ['y² - 25', 'y² - 5y + 25', 'y² - 10y + 25', 'y - 10'],
    correctAnswer: 2,
  },
  {
    id: 'math-9-3',
    subjectId: 'math',
    chapterId: 'alg',
    grade: '9',
    type: 'formula',
    topic: 'Difference of Squares',
    content: 'a² - b² = (a - b)(a + b)',
    question: 'How can you factorize 4x² - 9?',
    options: ['(4x - 3)(4x + 3)', '(2x - 3)(2x + 3)', '(2x - 9)(2x + 9)', 'Cannot be factorized'],
    correctAnswer: 1,
  },
  {
    id: 'math-9-4',
    subjectId: 'math',
    chapterId: 'alg',
    grade: '9',
    type: 'concept',
    topic: 'Linear Equation in One Variable',
    content: 'A linear equation in one variable can be written in the form ax + b = 0, where a and b are real numbers and a ≠ 0.',
    question: 'What is the value of x if 5x - 15 = 0?',
    options: ['5', '-3', '-5', '3'],
    correctAnswer: 3,
  },
  {
    id: 'math-9-5',
    subjectId: 'math',
    chapterId: 'alg',
    grade: '9',
    type: 'formula',
    topic: 'Product of Powers',
    content: 'When multiplying two powers with the same base, you can add the exponents: (x^m) * (x^n) = x^(m+n)',
    question: 'What is x³ * x⁵?',
    options: ['x¹⁵', 'x⁸', '2x⁸', 'x²'],
    correctAnswer: 1,
  },
  {
    id: 'math-9-6',
    subjectId: 'math',
    chapterId: 'alg',
    grade: '9',
    type: 'formula',
    topic: 'Power of a Power',
    content: 'To find a power of a power, you multiply the exponents: (x^m)^n = x^(mn)',
    question: 'What is (y⁴)²?',
    options: ['y⁶', 'y¹⁶', 'y⁸', '2y⁴'],
    correctAnswer: 2,
  },
  {
    id: 'math-9-7',
    subjectId: 'math',
    chapterId: 'alg',
    grade: '9',
    type: 'formula',
    topic: 'Zero Exponent',
    content: 'Any non-zero base raised to the power of zero is equal to 1: x⁰ = 1 (for x ≠ 0)',
    question: 'What is the value of 1,234,567⁰?',
    options: ['0', '1,234,567', '1', 'Undefined'],
    correctAnswer: 2,
  },

  // Grade 11 - Physics - Mechanics (7 items)
  {
    id: 'phy-11-1',
    subjectId: 'phy',
    chapterId: 'mech',
    grade: '11',
    type: 'formula',
    topic: "Newton's First Law (Inertia)",
    content: 'An object at rest stays at rest and an object in motion stays in motion with the same speed and in the same direction unless acted upon by an unbalanced force.',
    question: 'A book is sitting on a dashboard of a car that is stopped. When the car starts to move forward, the book slides off the dashboard. Which law explains this?',
    options: ["Newton's First Law", "Newton's Second Law", "Newton's Third Law", "Law of Gravitation"],
    correctAnswer: 0,
  },
  {
    id: 'phy-11-2',
    subjectId: 'phy',
    chapterId: 'mech',
    grade: '11',
    type: 'formula',
    topic: "Newton's Second Law",
    content: 'The acceleration of an object is directly proportional to the net force acting on it and inversely proportional to its mass. F = ma',
    question: 'A force of 20 N acts on an object of mass 5 kg. What is the acceleration?',
    options: ['4 m/s²', '0.25 m/s²', '100 m/s²', '15 m/s²'],
    correctAnswer: 0,
  },
  {
    id: 'phy-11-3',
    subjectId: 'phy',
    chapterId: 'mech',
    grade: '11',
    type: 'formula',
    topic: "Newton's Third Law",
    content: 'For every action, there is an equal and opposite reaction.',
    question: 'When you jump, you push on the ground and the ground pushes back on you. This is an example of which law?',
    options: ["Newton's First Law", "Newton's Second Law", "Newton's Third Law", "Conservation of Energy"],
    correctAnswer: 2,
  },
  {
    id: 'phy-11-4',
    subjectId: 'phy',
    chapterId: 'mech',
    grade: '11',
    type: 'concept',
    topic: 'Momentum',
    content: 'Momentum is the product of the mass and velocity of an object (p = mv). It is a vector quantity.',
    question: 'A 1000 kg car is moving at 20 m/s. What is its momentum?',
    options: ['50 kg⋅m/s', '20,000 kg⋅m/s', '0.02 kg⋅m/s', '20,000 N'],
    correctAnswer: 1,
  },
  {
    id: 'phy-11-5',
    subjectId: 'phy',
    chapterId: 'mech',
    grade: '11',
    type: 'concept',
    topic: 'Work',
    content: 'Work is done when a force that is applied to an object moves that object. W = Fd cos(θ).',
    question: 'If you push a wall with all your might but it doesn\'t move, how much work have you done on the wall?',
    options: ['A large amount', 'A small amount', 'Zero', 'It depends on the force'],
    correctAnswer: 2,
  },
  {
    id: 'phy-11-6',
    subjectId: 'phy',
    chapterId: 'mech',
    grade: '11',
    type: 'concept',
    topic: 'Kinetic Energy',
    content: 'Kinetic Energy is the energy which an object possesses by virtue of its motion. KE = ½mv²',
    question: 'What happens to the kinetic energy of an object if its speed is doubled?',
    options: ['It is halved', 'It is doubled', 'It is quadrupled', 'It remains the same'],
    correctAnswer: 2,
  },
  {
    id: 'phy-11-7',
    subjectId: 'phy',
    chapterId: 'mech',
    grade: '11',
    type: 'concept',
    topic: 'Potential Energy',
    content: 'Potential Energy is the energy held by an object because of its position relative to other objects. Gravitational PE = mgh.',
    question: 'A 2 kg book is lifted 3 meters from the floor. What is its potential energy? (use g=9.8 m/s²)',
    options: ['6 J', '58.8 J', '19.6 J', '29.4 J'],
    correctAnswer: 1,
  },


  // Grade 10 - Chemistry - Organic Chemistry (7 items)
  {
    id: 'chem-10-1',
    subjectId: 'chem',
    chapterId: 'org',
    grade: '10',
    type: 'concept',
    topic: 'Hydrocarbons',
    content: 'Hydrocarbons are organic compounds consisting entirely of hydrogen and carbon atoms. Alkanes are the simplest type, with single C-C bonds.',
    question: 'Which of the following is an alkane?',
    options: ['C₂H₄ (Ethene)', 'C₂H₂ (Ethyne)', 'C₂H₆ (Ethane)', 'C₆H₆ (Benzene)'],
    correctAnswer: 2,
  },
  {
    id: 'chem-10-2',
    subjectId: 'chem',
    chapterId: 'org',
    grade: '10',
    type: 'concept',
    topic: 'Alkenes',
    content: 'Alkenes are hydrocarbons that have at least one carbon-carbon double bond (C=C).',
    question: 'What is the general formula for alkenes?',
    options: ['CₙH₂ₙ₊₂', 'CₙH₂ₙ', 'CₙH₂ₙ₋₂', 'CₙHₙ'],
    correctAnswer: 1,
  },
  {
    id: 'chem-10-3',
    subjectId: 'chem',
    chapterId: 'org',
    grade: '10',
    type: 'concept',
    topic: 'Alkynes',
    content: 'Alkynes are hydrocarbons that have at least one carbon-carbon triple bond (C≡C).',
    question: 'Which molecule contains a triple bond?',
    options: ['Propane', 'Propene', 'Propyne', 'Cyclopropane'],
    correctAnswer: 2,
  },
  {
    id: 'chem-10-4',
    subjectId: 'chem',
    chapterId: 'org',
    grade: '10',
    type: 'concept',
    topic: 'Functional Groups',
    content: 'A functional group is a specific group of atoms within a molecule that is responsible for the characteristic chemical reactions of that molecule. Example: -OH (hydroxyl group) in alcohols.',
    question: 'The functional group -COOH is characteristic of which class of organic compounds?',
    options: ['Alcohols', 'Aldehydes', 'Ketones', 'Carboxylic Acids'],
    correctAnswer: 3,
  },
  {
    id: 'chem-10-5',
    subjectId: 'chem',
    chapterId: 'org',
    grade: '10',
    type: 'concept',
    topic: 'Isomers',
    content: 'Isomers are compounds that have the same molecular formula but different structural formulas.',
    question: 'Butane and Isobutane both have the formula C₄H₁₀. They are examples of:',
    options: ['Isotopes', 'Allotropes', 'Isomers', 'Polymers'],
    correctAnswer: 2,
  },
  {
    id: 'chem-10-6',
    subjectId: 'chem',
    chapterId: 'org',
    grade: '10',
    type: 'concept',
    topic: 'Saturated vs Unsaturated',
    content: 'Saturated hydrocarbons (alkanes) contain only single bonds. Unsaturated hydrocarbons (alkenes, alkynes) contain double or triple bonds.',
    question: 'Which of these hydrocarbons is saturated?',
    options: ['Ethene', 'Ethyne', 'Benzene', 'Ethane'],
    correctAnswer: 3,
  },
  {
    id: 'chem-10-7',
    subjectId: 'chem',
    chapterId: 'org',
    grade: '10',
    type: 'concept',
    topic: 'Polymers',
    content: 'Polymers are large molecules (macromolecules) composed of many repeated subunits, known as monomers.',
    question: 'Polyethylene is a polymer made from which monomer?',
    options: ['Ethane', 'Ethene', 'Ethyne', 'Ethanol'],
    correctAnswer: 1,
  },
  
  // Grade 12 - Biology - Cell Biology (7 items)
  {
    id: 'bio-12-1',
    subjectId: 'bio',
    chapterId: 'cell',
    grade: '12',
    type: 'term',
    topic: 'Mitochondria',
    content: 'Often called the "powerhouses" of the cell, mitochondria are organelles that generate most of the cell\'s supply of adenosine triphosphate (ATP), used as a source of chemical energy.',
    question: 'What is the primary function of mitochondria?',
    options: ['Store genetic material', 'Synthesize proteins', 'Generate energy (ATP)', 'Control cell division'],
    correctAnswer: 2,
  },
  {
    id: 'bio-12-2',
    subjectId: 'bio',
    chapterId: 'cell',
    grade: '12',
    type: 'term',
    topic: 'Nucleus',
    content: 'The nucleus is a membrane-bound organelle that contains the cell\'s genetic material (DNA). It controls the cell\'s growth and reproduction.',
    question: 'Which organelle is considered the "control center" of the cell?',
    options: ['Ribosome', 'Nucleus', 'Endoplasmic Reticulum', 'Golgi Apparatus'],
    correctAnswer: 1,
  },
  {
    id: 'bio-12-3',
    subjectId: 'bio',
    chapterId: 'cell',
    grade: '12',
    type: 'term',
    topic: 'Ribosomes',
    content: 'Ribosomes are responsible for protein synthesis. They can be found floating freely in the cytoplasm or attached to the endoplasmic reticulum.',
    question: 'Where does protein synthesis occur in a cell?',
    options: ['Mitochondria', 'Lysosomes', 'Vacuoles', 'Ribosomes'],
    correctAnswer: 3,
  },
  {
    id: 'bio-12-4',
    subjectId: 'bio',
    chapterId: 'cell',
    grade: '12',
    type: 'term',
    topic: 'Cell Membrane',
    content: 'The cell membrane is a semipermeable barrier that surrounds the cytoplasm of a cell, controlling the passage of substances in and out.',
    question: 'What is the main role of the cell membrane?',
    options: ['To provide rigid support', 'To control what enters and leaves the cell', 'To produce energy', 'To store water'],
    correctAnswer: 1,
  },
  {
    id: 'bio-12-5',
    subjectId: 'bio',
    chapterId: 'cell',
    grade: '12',
    type: 'term',
    topic: 'Chloroplasts',
    content: 'Chloroplasts are organelles found in plant cells and eukaryotic algae that conduct photosynthesis.',
    question: 'In which type of cell would you expect to find chloroplasts?',
    options: ['Animal cell', 'Bacterial cell', 'Fungal cell', 'Plant cell'],
    correctAnswer: 3,
  },
  {
    id: 'bio-12-6',
    subjectId: 'bio',
    chapterId: 'cell',
    grade: '12',
    type: 'term',
    topic: 'Endoplasmic Reticulum (ER)',
    content: 'The ER is a network of membranes involved in protein and lipid synthesis. The rough ER is studded with ribosomes, while the smooth ER is not.',
    question: 'The presence of ribosomes on the rough ER indicates it is involved in what process?',
    options: ['Lipid synthesis', 'Detoxification', 'Protein synthesis', 'Carbohydrate storage'],
    correctAnswer: 2,
  },
  {
    id: 'bio-12-7',
    subjectId: 'bio',
    chapterId: 'cell',
    grade: '12',
    type: 'term',
    topic: 'Golgi Apparatus',
    content: 'The Golgi apparatus, or Golgi complex, is an organelle that modifies, sorts, and packages proteins and lipids for secretion or delivery to other organelles.',
    question: 'Which organelle acts like a "post office" for the cell?',
    options: ['Nucleus', 'Mitochondrion', 'Golgi Apparatus', 'Lysosome'],
    correctAnswer: 2,
  },
];
